version: "3.9"

services:
  app:
    build: .
    working_dir: /var/www/html
    volumes:
      - app_code:/var/www/html
      - laravel_storage:/var/www/html/storage
    depends_on:
      - mysql
    networks:
      - laravel_net

  nginx:
    build:
      context: ./docker/nginx
    expose:
      - "80"
    volumes:
      - app_code:/var/www/html:ro
    depends_on:
      - app
    networks:
      - laravel_net


  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: laravel_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  mysql_data:
  laravel_storage:
  app_code:
